export const cityAreas: Record<string, string[]> = {
  bangalore:  [
"Abbigere",
"Adugodi",
"AECS Layout",
"Akshayanagar",
"Amrutha Halli",
"Anagalapura",
"Anjanapura",
"Annapurneshwari Nagar",
"Andrahalli",
"Anekal",
"Arasanakunte",
"Ashirvad Colony",
"Ashok Nagar",
"Attibele",
"Attiguppe",
"Aavalahalli",
"Azad Nagar",
"B Narayanapura",
"Babusa Palya",
"Bagalakunte",
"Bagaluru",
"Bagepalli",
"Baiyyappanahalli",
"Balagere",
"Ballur",
"Banashankari",
"Banaswadi",
"Bannerghatta",
"Bapuji Nagar",
"Basapura",
"Basavanagar",
"Basavanagudi",
"Basavanna Nagar",
"Basaveshwara Nagar",
"Battarahalli",
"Begur",
"Belathur",
"Bellandur",
"Bennigana Halli",
"Benson Town",
"Bettahalasur",
"Bhaktharahalli",
"Bhoganhalli",
"Bhoopasandra",
"Bhovi Palya",
"Bidrahalli",
"Bidadi",
"Bikkanahalli",
"Bileshivale",
"Binny Pete",
"Bommasandra",
"Bommenahalli",
"Boyalahalli",
"Brigade Road",
"Brookefield",
"Budigere",
"Budihal",
"BTM Layout",
"Byatarayanapura",
"Byrathi",
"Cambridge Layout",
"Carmelaram",
"Chadalapura",
"Chamarajpet",
"Chamundi Nagar",
"Chandapura",
"Chandra Layout",
"Chansandra",
"Chelekare",
"Chikkaballapur",
"Chikka Banaswadi",
"Chikka Tirupathi",
"Chikkagubbi",
"Chikkajala",
"Chikkakannalli",
"Chikkalasandra",
"Chikkanahalli",
"Chikbanavara",
"Chikkathoguru",
"Chinnapa Garden",
"Chinnapanna Halli",
"Chintamani",
"Chokkanahalli",
"Cholanayakanahalli",
"Commercial Street",
"Cooke Town",
"Cottonpete",
"Cox Town",
"CQAL Layout",
"Craig Park Layout",
"CV Raman Nagar",
"Cunningham Road",
"Dabaspete",
"Dasarahalli Hebbal",
"Dasarahalli Main Road",
"Dayananda Nagar",
"Devanahalli",
"Devanahalli Road",
"Devarachikkanahalli",
"Devasthanagalu",
"Devinagar",
"Dodda Aalada Mara Road",
"Dodda Banasvadi",
"Doddabele",
"Doddabommasandra",
"Doddakallasandra",
"Doddakannalli",
"Doddakammanahalli",
"Doddathoguru",
"Dodsworth Layout",
"Domlur",
"Dommasandra",
"Dollars Colony",
"Dooravani Nagar",
"Ejipura",
"Electronic City",
"Essel Gardens",
"Frazer Town",
"Gandhi Nagar",
"Ganapathihalli",
"Ganga Nagar",
"Garden Layout",
"Garudachar Palya",
"Garvebhavi Palya",
"Gattahalli",
"Gauribidanur",
"Girinagar",
"GM Palya",
"Gollahalli",
"Gottigere",
"Gubalala",
"Gunjur",
"Gunjur Mugalur Road",
"Guttahalli",
"HAL Layout",
"Hancharahalli",
"Hanumantha Nagar",
"Haragadde",
"Harlur",
"Harohalli",
"Haudin Road",
"HBR Layout",
"Hebbal",
"Hegde Nagar",
"Hennur",
"Hennur Road",
"Hesaraghatta",
"HMT Layout",
"Hombegowda Nagar",
"Hongasandra",
"Horamavu",
"Horamavu Agara",
"Hosa Road",
"Hosakerehalli",
"Hosapalaya",
"Hoskote",
"Hosur Road",
"HSR Layout",
"Hulimavu",
"Hullahalli",
"Huskur",
"Huttanahalli",
"Immadihalli",
"Indira Nagar",
"Infantry Road",
"International Airport Road",
"ISRO Layout",
"ITPL Road",
"IVC Road",
"Jakkasandra",
"Jakkur",
"Jalahalli",
"Jangamakote",
"Jaya Chamarajendra Nagar",
"Jayamahal",
"Jayanagar",
"JP Nagar",
"Kadabagere",
"Kadubeesanahalli",
"Kadugodi",
"Kadugondanahalli",
"Kaggadasapura",
"Kaggalipura",
"Kaikondrahalli",
"Kalkere",
"Kalasipalayam",
"Kalena Agrahara",
"Kamaksipalya",
"Kamala Nagar",
"Kamanahalli",
"Kammasandra",
"Kanaka Nagar",
"Kanakapura",
"Kannamangala",
"Karthik Nagar",
"Kasturi Nagar",
"Kathriguppe",
"Kattigenahalli",
"Kaval Byrasandra",
"Kempegowda Nagar",
"Kempapura",
"Kengeri",
"Kithiganur",
"Kodathi",
"Kodichikkanahalli",
"Kodigehalli",
"Kodihalli",
"Kodipur",
"Kogilu",
"Kolar Road",
"Kolar-Chikkaballapur Road",
"Kommaghatta",
"Konanakunte",
"Koramangala",
"Koralur",
"Kothanur",
"Kothanoor",
"Koti Hosahalli",
"K R Puram",
"Krishnarajapuram",
"Kudlu",
"Kudlu Gate",
"Kumbalgodu",
"Kundalahalli",
"Kunigal Road",
"Kuthaganahalli",
"LB Shastri Nagar",
"Laggere",
"Lakshmamma Layout",
"Lake City",
"Langford Road",
"Langford Town",
"Lavelle Road",
"Lingarajapuram",
"Lingadheeranahalli",
"Madiwala",
"Madhava Nagar",
"Magadi Road",
"Mahadevapura",
"Mahalakshmi Layout",
"Majestic",
"Mallathahalli",
"Malleshpalya",
"Malleshwaram",
"Malur-Hosur Road",
"Marathahalli",
"Maruthi Nagar",
"Mathikere",
"Medihalli",
"Mico Layout",
"Millers Road",
"MG Road",
"Munireddy Layout",
"Munnekollal",
"Murugeshpalya",
"Mysore Road",
"Nagasandra",
"Nagadevanahalli",
"Nagarbhavi",
"Nagavara",
"Nagondanahalli",
"Nallurhalli",
"Nandi Hills",
"Nanjappa Garden",
"Narasapura",
"Nayanda Halli",
"Neelasandra",
"Neeladri Nagar",
"Nehru Nagar",
"Nelamangala",
"New BEL Road",
"New Thippasandra",
"Nobo Nagar",
"NRI Layout",
"Off Sarjapur road",
"Old Airport Road",
"Old Madras Road",
"OMBR Layout",
"Outer Ring Road",
"Padmanabha Nagar",
"Pai Layout",
"Palace Road",
"Panathur",
"Panduranga Nagar",
"Pattandur Agrahara",
"Peenya",
"Prashanth Nagar",
"Rachenahalli",
"Race Course Road",
"Raghavendra Colony",
"Ragavendra Nagar",
"Rajaji Nagar",
"Rajanukunte",
"Rajiv Gandhi Nagar",
"Raja Rajeshwari Nagar",
"Ramagondanahalli",
"Ramamurthy Nagar",
"Ramohalli",
"Rayasandra",
"Residency Road",
"Rest House Road",
"Richards Town",
"Richard's Park",
"Richmond Road",
"Richmond Town",
"Roopena Agrahara",
"RT Nagar",
"S.Medihalli",
"Sadashiva Nagar",
"Sadduguntepalya",
"Sahakara Nagar",
"Sampangi Rama Nagar",
"Sampigehalli",
"Sanjay Nagar",
"Sankey Road",
"Sarjapur",
"Sarjapur Road",
"Seegehalli",
"Seenappa Layout",
"Seshadripuram",
"Shankarapura",
"Shanthi Nagar",
"Shanthi Pura",
"Shanthala Nagar",
"Shettihalli",
"Shigehalli",
"Shivaji Nagar",
"Siddapura",
"Silk Board",
"Silver Springs Layout",
"Singanahalli",
"Singasandra",
"SMV Layout",
"Solur",
"Somashetti Halli",
"Sompura",
"Sonnenahalli",
"Soundarya Layout",
"Soukya Road",
"Srinagar",
"Srinivasa Nagar",
"Srirampura",
"St. Johns Road",
"Subramanyapura",
"Sudhama Nagar",
"Sunkadakatte",
"Suryanagar",
"T Dasarahalli",
"Talaghattapura",
"Tavarekere-BTM",
"TC Palya Road",
"Teacher's Colony",
"Tharabanahalli",
"Tharaballi",
"Thanisandra",
"Thippasandra",
"Thubarahalli",
"Tippenahalli",
"Tilak Nagar",
"Tumkur Road",
"Ulsoor",
"Ullal",
"Uttarahalli",
"Vaderahalli",
"Varthur",
"Vasanth Nagar",
"Vasanthapura",
"Venkatagiri Kote",
"Venkatapura",
"Venkateshpuram",
"Victoria Layout",
"Vidyaranyapura",
"Vignana Nagar",
"Vijaya Bank Colony",
"Vijayanagar",
"Vijaypura",
"Vinayaka Layout",
"Virupakshapura",
"Vishweshwaraiah Layout",
"Vittal Nagar",
"Viveka Nagar",
"Wheeler Road",
"Whitefield",
"Williams Town",
"Wind Tunnel Road",
"Yelahanka",
"Yelanahalli",
"Yemalur",
"kalyan nagar"
],
   tirupati: [
  "Balaji Colony",
  "Bhavani Nagar",
  "Bairagipatteda",
  "Renigunta Road",
  "Air Bypass Road",
  "Mangalam",
  "Mangalam Road",
  "Padmavathi Nagar",
  "Korlagunta",
  "Maruthi Nagar",
  "Nehru Nagar",
  "Ramnagar",
  "Royal Nagar",
  "Sai Nagar",
  "Srinivasa Nagar",
  "Vivekananda Nagar",
  "Ashok Nagar",
  "Avilala",
  "Chandragiri",
  "Chandragiri Road",
  "Daminedu",
  "Tiruchanur",
  "Tiruchanur Road",
  "Perur",
  "Peruru Road",
  "Kapila Theertham",
  "KT Road",
  "MR Palli",
  "Reddy & Reddy Colony",
  "SV University Area",
  "Sri Padmavathi Mahila University Area",
  "Tata Nagar",
  "Annarao Circle",
  "Leela Mahal Circle",
  "Old Tirupati",
  "New Tirupati",
  "Settipalli",
  "Yerpedu",
  "Renigunta",
  "Renigunta Industrial Area",
  "Auto Nagar",
  "RC Road",
  "Alipiri",
  "Alipiri Road",
  "Vinayaka Nagar",
  "Karakambadi Road",
  "Subramanyam Nagar",
  "Lakshmipuram",
  "Madhura Nagar"
],
  warangal: [
  "Hanamkonda",
  "Kazipet",
  "Subedari",
  "Balasamudram",
  "Nakkalagutta",
  "Kishanpura",
  "Lashkar Singaram",
  "Deshaipet",
  "Waddepally",
  "Kothawada",
  "Ramnagar",
  "Saraswathi Nagar",
  "Kakatiya Colony",
  "Shyampet",
  "Hunter Road",
  "JPN Road",
  "MG Road",
  "Bus Stand Road",
  "Railway Station Road",
  "NGO Colony",
  "Gopalpur",
  "KUC Road",
  "Kakatiya University Area",
  "Bheemaram",
  "Enumamula",
  "Enumamula Market Yard",
  "Mulugu Road",
  "Nayeem Nagar",
  "Shivanagar",
  "Pochamma Maidan",
  "Warangal Fort Area",
  "Bhadrakali Temple Area",
  "Mamnoor",
  "Mamnoor Industrial Area",
  "Dharmasagar",
  "Hasanparthy",
  "Madikonda",
  "Kashibugga",
  "Reddypuram",
  "Vijaya Talkies Area",
  "Matwada",
  "Giriprasad Nagar",
  "Subhash Nagar",
  "Siddhartha Nagar",
  "SR Nagar",
  "Teachers Colony",
  "LB Nagar",
  "Sai Nagar",
  "Auto Nagar"
],
    guntur: [
  "Arundelpet",
  "Brodipet",
  "Lakshmipuram",
  "Kothapet",
  "Pattabhipuram",
  "Sampath Nagar",
  "Vidyanagar",
  "Nehru Nagar",
  "AT Agraharam",
  "Chandramouli Nagar",
  "Navabharat Nagar",
  "Gorantla",
  "Gorantla Extension",
  "Reddypalem",
  "Syamala Nagar",
  "Brindavan Gardens",
  "Srinagar Colony",
  "Autonagar",
  "Etukuru Road",
  "Nallapadu",
  "Nallapadu Road",
  "Buddampadu",
  "Tadepalli",
  "Tadepalli Road",
  "Lam",
  "Lam Farm Area",
  "Pedakakani",
  "Pedakakani Industrial Area",
  "Mangalagiri",
  "Mangalagiri Road",
  "Kaza",
  "Chuttugunta",
  "Old Guntur",
  "New Guntur",
  "Nagarampalem",
  "Sangadigunta",
  "Collector Office Road",
  "Railpet",
  "Donka Road",
  "Jinnah Tower Area",
  "Venkata Swamy Nagar",
  "KVP Colony",
  "Subhani Nagar",
  "Mallikarjuna Pet",
  "Bharath Pet",
  "RTC Colony",
  "SVN Colony",
  "Koritepadu"
],

  chennai: [
  "T Nagar",
  "Anna Nagar",
  "Adyar",
  "Velachery",
  "Tambaram",
  "Porur",
  "Ambattur",
  "Avadi",
  "Mylapore",
  "Triplicane",
  "Guindy",
  "Ashok Nagar",
  "KK Nagar",
  "Vadapalani",
  "Kodambakkam",
  "Valasaravakkam",
  "Virugambakkam",
  "Mogappair",
  "Kolathur",
  "Perambur",
  "Vyasarpadi",
  "Royapuram",
  "Washermanpet",
  "George Town",
  "Parrys Corner",
  "Mount Road",
  "Nungambakkam",
  "Egmore",
  "Chetpet",
  "Kilpauk",
  "Purasaiwalkam",
  "Choolai",
  "Chintadripet",
  "Saidapet",
  "West Mambalam",
  "Alwarpet",
  "Besant Nagar",
  "Thiruvanmiyur",
  "Perungudi",
  "Sholinganallur",
  "Navalur",
  "Karapakkam",
  "Injambakkam",
  "ECR",
  "OMR",
  "Medavakkam",
  "Pallikaranai",
  "Madipakkam",
  "Chromepet",
  "Pallavaram",
  "Thoraipakkam",
  "Manapakkam",
  "Nandambakkam",
  "Red Hills",
  "Madhavaram",
  "Manali",
  "Ennore",
  "Tondiarpet",
  "Thirumangalam",
  "Koyambedu",
  "Aminjikarai",
  "Kotturpuram",
  "Kovilambakkam",
  "Urapakkam",
  "Guduvanchery",
  "Sriperumbudur",
  "Oragadam",
  "Poonamallee",
  "Thiruvottiyur",
  "Thiruninravur"
],

  hyderabad:[
  "A G Colony",
  "A S Rao Nagar",
  "Aaditya Nagar",
  "Abdullapurmet",
  "Abids",
  "AC Guards",
  "Adarsh Enclave",
  "Adarsh Nagar",
  "Afzalgunj",
  "Aghapura",
  "Ahmed Nagar",
  "Akbar Road",
  "Alexander Road",
  "Aliabad",
  "Alkapur Township",
  "Almasguda",
  "Alwal",
  "Ambedkar Nagar",
  "Amber Nagar",
  "Amberpet",
  "Ameerpet",
  "Ameerpet X Road",
  "Anand Bagh",
  "Anand Nagar Colony",
  "Ananthagiri",
  "Ankireddypalli",
  "Appa Junction",
  "AS Rao Nagar",
  "Ashok Nagar",
  "Asif Nagar",
  "Athvelly",
  "Attapur",
  "Attapur Ring Road",
  "Auto Nagar",
  "Azamabad",
  "Azampura",
  "Baber Bagh",
  "Bachupally",
  "Badangpet",
  "Badichowdi",
  "Bag Amberpet",
  "Bagh Lingampally",
  "Bahadurpally",
  "Bahadurpura",
  "Bairamalguda",
  "Bakaram",
  "Balamrai",
  "Balanagar",
  "Balapur",
  "Balkampet",
  "Bandimet",
  "Bandlaguda",
  "Bandlaguda Jagir",
  "Banjara Hills",
  "Bansilalpet",
  "Bapuji Nagar",
  "Barkas",
  "Barkatpura",
  "Basheer Bagh",
  "Bazar Ghat",
  "Begum Bazaar",
  "Begumpet",
  "Bhagya Nagar Colony",
  "Bharat Nagar",
  "BHEL",
  "Bhogaram",
  "Bholakpur",
  "Bhongir",
  "Bhuvanagiri",
  "Bibinagar",
  "BK Guda",
  "BN Reddy Nagar",
  "Boduppal",
  "Bogaram",
  "Boggulakunta",
  "Boiguda",
  "Bolarum",
  "Bollaram",
  "Bongloor",
  "Borabanda",
  "Bowenpally",
  "Bowrampet",
  "Boyiguda",
  "Brahim Patnam",
  "Buddha Nagar",
  "Budwel",
  "Burgul",
  "Champapet",
  "Chanda Nagar",
  "Chandanagar",
  "Charminar",
  "Chikkadpally",
  "Chinta Basti",
  "Chintal",
  "Chinthal Basti",
  "Chiran Fort Clubra",
  "Chowmohalla",
  "Dabeerpura",
  "Dabeerpura North",
  "Dadar Colony",
  "Dammaiguda",
  "Darul Shifa",
  "Defence Colony",
  "Devan Devdi",
  "Dhoolpet",
  "Dilsukhnagar",
  "Doddapet",
  "Doodh Bowli",
  "Domalguda",
  "Domara Pocham Pally",
  "Dorabavi",
  "Durga Bhawani Nagar",
  "ECIL",
  "Ecil Post",
  "Ecil X Roads",
  "East Anandbagh",
  "East Marredpally",
  "Erragadda",
  "Erramanzil",
  "Film Nagar",
  "Gachibowli",
  "Gaddiannaram",
  "Ganapathi Nagar",
  "Gandhi Nagar",
  "Ghoshamahal",
  "Golconda",
  "Gopanpally",
  "Gowliguda",
  "Goud Nagar",
  "Gulzar Houz",
  "Gummadidala",
  "Hafeezpet",
  "Hakeempet",
  "Hajipalle",
  "Hanuman Nagar",
  "Hans Nagar",
  "Happy Homes Colony",
  "Haripuri Colony",
  "Hayath Nagar",
  "HCL Colony",
  "HMT Colony",
  "HMT Hills",
  "Himayath Nagar",
  "Hussaini Alam",
  "Hyderguda",
  "IDPL Colony",
  "IDC Colony",
  "Ibrahim Bagh",
  "Ibrahimpatnam",
  "Icrisat Enclave",
  "Indira Nagar",
  "Indira Nagar Colony",
  "Inole",
  "Ismailkhanpet",
  "Jahanuma",
  "Jaihindpuram",
  "Jameen Bazar",
  "Jubilee Hills",
  "JNTU Colony",
  "Kachiguda",
  "Kalkaji Colony",
  "Kamala Nagar",
  "Kamalapuri Colony",
  "Kavadiguda",
  "Kavuri Hills",
  "Keerthanagar",
  "Khairatabad",
  "Kollur",
  "Kondapur",
  "Kothaguda",
  "Kothapet",
  "KPHB Colony",
  "Kukatpally",
  "Kukatpally Housing Board",
  "Lakdikapul",
  "Lingampally",
  "Madhapur",
  "Madhura Nagar",
  "Mahendra Hills",
  "Malkajgiri",
  "Malakpet",
  "Manikonda",
  "Maruthi Nagar",
  "Miyapur",
  "Moghalpura",
  "Moula Ali",
  "Mulugu",
  "Moti Nagar",
  "Nagole",
  "Nallakunta",
  "Nallagandla",
  "Narayanaguda",
  "Nasrullahpura",
  "Naya Nagar",
  "Nehru Nagar",
  "Neredmet",
  "Nizampet",
  "NTR Nagar",
  "Old Alwal",
  "Osman Nagar",
  "Padmarao Nagar",
  "Panjagutta",
  "Parsigutta",
  "Patancheru",
  "Peerzadiguda",
  "Picket",
  "Pillalaramaram",
  "Pochampally",
  "Punjagutta",
  "Puppalaguda",
  "Quthbullapur",
  "Rahmania Nagar",
  "Raghavendra Nagar Colony",
  "Rajendranagar",
  "Ramanthapur",
  "Ramnagar",
  "Red Hills",
  "RTC X Roads",
  "Sainikpuri",
  "Sanathnagar",
  "Santosh Nagar",
  "Secunderabad",
  "Shadnagar",
  "Shamirpet",
  "Shantinagar",
  "Shamshabad",
  "Shivamguda",
  "Siddiq Nagar",
  "Sitaphalmandi",
  "SR Nagar",
  "SRT Colony",
  "Tadbund",
  "Talaab Katta",
  "Talabkatta",
  "Taramatipet",
  "Tarnaka",
  "Tellapur",
  "Toli Chowki",
  "Uppal",
  "Uppal Kalan",
  "Usha Nagar",
  "Vanasthalipuram",
  "Vattepally",
  "Vengal Rao Nagar",
  "Vidyanagar",
  "Warasiguda",
  "West Marredpally",
  "Yadagirigutta",
  "Yakutpura",
  "Yapral",
  "Yellareddy Guda",
  "Yousufguda",
  "Zameerbagh",
  "Zamistanpur",
  "Hitech City",
  "Hi Tech City",
  "Jeedimetla",
  "Financial District",
  "Nanakramguda",
  "Raidurg",
  "Raidurgam",
  "Kokapet",
  "Narsingi",
  "Tellapur Phase 2",
  "Kompally",
  "Medchal",
  "Suchitra",
  "Suchitra Circle",
  "Keesara",
  "Turkapally",
  "Pocharam",
  "Pocharam IT Park",
  "Adibatla",
  "Tukkuguda",
  "Maheshwaram",
  "Shankarpally",
  "Kothur",
  "Chevella",
  "Moinabad",
  "Gandipet",
  "Neknampur",
  "Alkapuri",
  "Kapra",
  "Safilguda",
  "Dr AS Rao Nagar",
  "Chintalakunta",
  "Meerpet",
  "LB Nagar X Roads",
  "Hasthinapuram",
  "Karmanghat",
  "Moosapet",
  "Pragathi Nagar",
  "Mallapur",
  "Nacharam",
  "Upparpally",
  "Santoshnagar Colony",
  "Raj Bhavan Road",
  "Somajiguda",
  "Greenlands",
  "Begumpet Airport Area",
  "Trimulgherry",
  "Mettuguda",
  "Tarnaka X Roads",
  "Secunderabad Cantonment"
],

  coimbatore: [
  "RS Puram",
  "Gandhipuram",
  "Saibaba Colony",
  "Race Course",
  "Town Hall",
  "Ukkadam",
  "Sundarapuram",
  "Kuniamuthur",
  "Podanur",
  "Singanallur",
  "Ramanathapuram",
  "Peelamedu",
  "Hope College",
  "Avinashi Road",
  "Lakshmi Mills",
  "Chinniyampalayam",
  "Kalapatti",
  "Saravanampatti",
  "Thudiyalur",
  "Koundampalayam",
  "Vadakovai",
  "Ganapathy",
  "Sivananda Colony",
  "Tatabad",
  "PN Pudur",
  "Edayarpalayam",
  "Vadavalli",
  "Veerakeralam",
  "Perur",
  "Selvapuram",
  "Kovaipudur",
  "Madukkarai",
  "Malumichampatti",
  "Chettipalayam",
  "Neelambur",
  "Irugur",
  "Sulur",
  "Annur",
  "Mettupalayam Road",
  "Karamadai",
  "Eachanari",
  "Kurichi",
  "Ondipudur",
  "Goldwins",
  "Nava India",
  "Vellalore",
  "Thirumalayampalayam",
  "Vilankurichi",
  "Udayampalayam",
  "KNG Pudur"
],

  mysuru:  [
  "Vijayanagar",
  "Jayalakshmipuram",
  "Saraswathipuram",
  "Gokulam",
  "Lakshmipuram",
  "Nazarbad",
  "Kuvempunagar",
  "Dattagalli",
  "Jayanagar",
  "Bogadi",
  "Hunsur Road",
  "Hebbal",
  "Brindavan Extension",
  "Yadavagiri",
  "Vontikoppal",
  "Bannimantap",
  "Siddarthanagar",
  "Rajiv Nagar",
  "Udayagiri",
  "Chamundipuram",
  "Ashokapuram",
  "NR Mohalla",
  "Shivarampet",
  "Agrahara",
  "KRS Road",
  "Metagalli",
  "Belavadi",
  "Ilavala",
  "Alanahalli",
  "Srirampura",
  "JP Nagar",
  "Hootagalli",
  "Kalyanagiri",
  "Kuvempunagar North",
  "Lingambudhi Palya",
  "Chamundi Hill Road",
  "Dattagalli 2nd Stage",
  "Kuvempunagar 1st Stage",
  "Vijayanagar 2nd Stage",
  "Vijayanagar 3rd Stage"
],

  vijayawada: [
  "Benz Circle",
  "MG Road",
  "Labbipet",
  "Governorpet",
  "Suryaraopet",
  "Patamata",
  "Gurunanak Colony",
  "Tikkle Road",
  "Auto Nagar",
  "Kanuru",
  "Poranki",
  "Penamaluru",
  "Ramavarappadu",
  "Currency Nagar",
  "Bhavanipuram",
  "Vidhyadharapuram",
  "One Town",
  "Krishnalanka",
  "Christurajupuram",
  "Kedareswarapet",
  "Ajit Singh Nagar",
  "Payakapuram",
  "Kamakoti Nagar",
  "Machavaram",
  "Gunadala",
  "Singhnagar",
  "Nunna",
  "Gollapudi",
  "Ibrahimpatnam",
  "Enikepadu",
  "Kankipadu",
  "Mangalagiri",
  "Tadepalli",
  "Undavalli",
  "Yanamalakuduru",
  "Chittinagar",
  "Buckinghampet",
  "Satyanarayanapuram",
  "LIC Colony",
  "Ravindra Nagar"
],

  visakhapatnam:[
  "MVP Colony",
  "Madhurawada",
  "Rushikonda",
  "Yendada",
  "PM Palem",
  "Seethammadhara",
  "Dwaraka Nagar",
  "Asilmetta",
  "Siripuram",
  "Waltair Uplands",
  "Lawsons Bay Colony",
  "Beach Road",
  "Jagadamba Junction",
  "Maharani Peta",
  "Ramakrishna Beach",
  "Gajuwaka",
  "Akkayyapalem",
  "NAD Junction",
  "Gopalapatnam",
  "Simhachalam",
  "Pendurthi",
  "Anandapuram",
  "Bheemili",
  "Tagarapuvalasa",
  "Arilova",
  "HB Colony",
  "Muralinagar",
  "Kommadi",
  "Vepagunta",
  "Kancharapalem",
  "Railway New Colony",
  "Allipuram",
  "Poorna Market",
  "One Town",
  "Old Post Office",
  "Pedagantyada",
  "Kurmannapalem",
  "Duvvada",
  "Steel Plant",
  "Scindia",
  "Town Kotha Road"
],
  rajahmundry: [
  "Danavaipeta",
  "T Nagar",
  "Aryapuram",
  "Kotagummam",
  "Innespeta",
  "Prakash Nagar",
  "Syamala Nagar",
  "Sriramnagar",
  "Venkateswara Nagar",
  "Lalacheruvu",
  "Hukumpeta",
  "Katheru",
  "Dowleswaram",
  "Morampudi",
  "VL Puram",
  "Spinning Mill Colony",
  "Bommuru",
  "Diwan Cheruvu",
  "Kolamuru",
  "Gadala",
  "Seethampeta",
  "RTC Complex Area",
  "Gunduvari Street",
  "Main Road",
  "Jampeta",
  "Tilak Road",
  "Kambala Cheruvu",
  "Railway Station Road",
  "Alcot Gardens",
  "Pushkar Ghat",
  "Gollaprolu Road",
  "Burugupudi Road",
  "Round Park",
  "Danavaipeta Extension",
  "Anala Venkatappa Rao Road",
  "Government Hospital Area",
  "Pydiparru",
  "Kondagudem",
  "Nallamilli"
],
  nellore: [
  "Magunta Layout",
  "Balaji Nagar",
  "Vedayapalem",
  "Brindavan Colony",
  "Dargamitta",
  "Mini Bypass Road",
  "Podalakur Road",
  "Stonehousepet",
  "Fathekhanpet",
  "VRC Centre",
  "AC Subba Reddy Stadium Area",
  "Mulapet",
  "Harindra Nagar",
  "Netaji Nagar",
  "Raghava Reddy Colony",
  "Gandhi Nagar",
  "Allipuram",
  "Kavali Road",
  "Atmakur Road",
  "Ramji Nagar",
  "Kakutur",
  "Chinthareddypalem",
  "BV Nagar",
  "Tikkavarapu Street",
  "Trunk Road",
  "Kothur",
  "Islampet",
  "Venkatachalam",
  "Buja Buja Nellore",
  "Muthukur Road",
  "Padarupalli",
  "Kondayapalem",
  "Kovur",
  "Nawabpet",
  "Police Colony",
  "RTC Bus Stand Area",
  "Mypadu Road",
  "Gudur Road",
  "SPSR Nellore Rural",
  "Navodaya Colony"
],
anakapalli : [
  "Gavarapalem",
  "Woodpeta",
  "Ring Road",
  "Sarada Colony",
  "NTR Colony",
  "Vivekananda Colony",
  "Ramnagar",
  "Subbavaram Road",
  "Kunchangi",
  "Kasimkota Road",
  "Revidi",
  "Munagapaka",
  "Kothapalli",
  "Gajuwaka Road",
  "Vepagunta Road",
  "Railway Station Area",
  "Main Road",
  "Market Area",
  "Gollaprolu Junction",
  "Chintapalli Road",
  "Kovvada",
  "Tagarapuvalasa Road",
  "Kothuru",
  "Akkireddypalem",
  "Anakapalli Rural",
  "Narsipatnam Road",
  "Bheemili Road",
  "RTC Complex Area",
  "Old Bus Stand Area",
  "New Bus Stand Area"
],
tuni:[
  "Main Road",
  "Railway Station Road",
  "Bus Stand Area",
  "Market Area",
  "Kothapeta",
  "Gandhi Nagar",
  "Balaji Nagar",
  "Ramnagar",
  "Indira Nagar",
  "Venkateswara Colony",
  "Annavaram Road",
  "Payakaraopeta Road",
  "Tuni Rural",
  "Nandivada",
  "Velama Kothuru",
  "Hamsavaram",
  "K.O. Mallavaram",
  "Komaravaram",
  "S. Annavaram",
  "Tuni Old Town",
  "Tuni New Colony",
  "RTC Complex Area",
  "Industrial Area",
  "Kummarilova Road",
  "Raghunathapuram"
],
};
